services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go
  db:
    image: alpine/sqlite:latest
    ports:
      - "5432:5432"
    volumes:
      - sqlite-db:/var/lib/postgresql/data

volumes:
  sqlite-db: